sudo: false
language: go
services:
- docker
branches:
- develop
- master
- feature/*
env:
  heroku:
    secure: ooZdKe5q1GyHCNNWJJ/BJ5W5OwjrjSZdrju9UbiG/rM8zoCGpHnN/IhlVvWDxYlgbTWzZdf1oRoID9zZAFwcmT6cisvOFEvUuJZOXE6ZSu3Pl7o+P4byx51LWB4wcBNnRT1lSpr5ArAqs7YWr4u7jjhio7HQ1jc1+x4HOQq7gxbf8pYCZ73sM6J6ZSiAcFvR35pVbVeYxPbBjB8qHmugL08ZuCx2v+pMlSSxBf2rscvkG+A/sSCQp80LxgO72F6b3tkdLZgsrI/IfOvujToz2DKTkfOCsEfjquzvTrZGFFc+xRKAx3jVdR9hFfpmTKgHrWSEMwmyM8k00AvyGaYH7jJd1OlsiZtn9BtUUg+0sHICTKcjmHrz0KD0qxnvYWWtyDwuvKXQNE0DRne7SU3TyvaEzVVVfgNOXtWDnUE4IKT9GIRNG9s+eUEr/DFFxUsVAyUsExJURk5K/+NKrHZ94yqXjhEjx2us6dQ42FVImFsMpKnx1tfW8q0Dh4xS+TzwsxLIzEwn1OoTKgQIxoCrTg8I8gXfNEu9d+lrd7j7eKxC9jQq85qtaunU0pYxNiP1N2X7edhIp1YOaTOgiqhXbTrhfEUcSmIohYzVaZ/I0R9slywyhUISP5W2yh+6QegB85A2CW4nuqahmrGl9bnf0QIGnSUxoh9xVY5eBgCkqwM=
    APP_NAME : damp-ravine-74691
go:
- 1.10.x
before_install:
- export GOPATH=$HOME/gopath/src/github.com/ratoshniuk/galcon-backend-go
- export PATH=$HOME/gopath/bin:$PATH
- chmod +x dep.sh
- "./dep.sh"
script:
- echo "$(git log | head -1)" > $GOPATH/revision.txt
- echo "$heroku.APP_NAME"
- go test -timeout 600s -v ./src/galcon-backend-go/...
