sudo: false
language: go
branches:
- develop
- master
- feature/*
env:
- FOO=$FOO
go:
- 1.10.x
before_install:
- export GOPATH=$HOME/gopath/src/github.com/ratoshniuk/galcon-backend-go
- export PATH=$HOME/gopath/bin:$PATH
- chmod +x dep.sh
- "./dep.sh"
script:
- go test -timeout 600s -v ./src/galcon-backend-go/...
deploy:
  provider: heroku
  on:
    branch: develop
  api_key:
    secure: FC4KhVGYaDpbYUNMSNXaktkMkG2SSMSxlkAw4BoDhFFWwYWox872yYl8h68sOnQirNqRTJ2SENbtS7nSG353C6TL+FvMBqJhWcXbQWi3d1SyqDFbvgz3+xXuob0BQy7VLAxs5MB1vAhkjXCRKPmanqBwA+QXOPeMSpZDf/x824Yw1JqOyQx4ts1NcQ80o9aBui/caODiGM1GtQhGQGzWuUX3m7GRGZcwBg8sDSidkZQfAYkglzGjo5ZsdL85ikSwF5OBYdlOeV+6HQgIPVjRijTslEukQTVTq9KdW5iQS4GoZrnRKz+j7WBG+V3aVXkMSRWQW8u+BT+IGyjOohtSQFj3xiTF2m0gnXyF/WeWdrD4uWcjitga8kIuVsB4Rmcfs6xIxT4Krq+hk7oeocvzKSIbGBZ55LZxjOaxa0vQYBiEkK6EJHV09v+eyndYOysItCHCs2hriN016goGPUf1QO8WG8c3i76i56uB0i7VEotltOJ2BJi9gGChnAkWOBQHORyQyAVex4lmKPpoOh9Y77LpdcWh5cZ/IqdM0f/pM0aIV7SL69PQ6eG2sRUvq3plhCjyJWvBrAFw2eG3MwiVWzg5wVVjW6WYvYMd787cI4+C0KZq7u5LvqPql33zOX/hP48TM/Y85ZvR4OJlAXR33AthlVtsaMMHmr8GYUvXe4Q=
